name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ "**" ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
          
      - name: Install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@10.15.1 --activate
        
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22.12.0
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i --frozen-lockfile
          
      - name: Format check (Biome)
        run: pnpm format:check

  test:
    runs-on: ubuntu-latest
    needs: [format]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
          
      - name: Install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@10.15.1 --activate
        
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22.12.0
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      
      - name: Generate features (web-features -> features.ts)
        run: pnpm gen:features

      - name: Build
        run: pnpm build

      - name: Type check
        run: pnpm typecheck

      - name: Run tests
        run: pnpm test
