name: Release

on:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      # id-token: write  # TODO OIDC
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@10.15.1 --activate
        
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install latest npm
        run: |
          echo "Current npm version: $(npm -v)"
          npm install -g npm@latest
          echo "Updated npm version: $(npm -v)"

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Generate features (web-features -> features.ts)
        run: pnpm gen:features

      - name: Build
        run: pnpm build

      - name: Run tests
        run: pnpm test

      - name: Generate coverage report (docs/coverage.md)
        run: pnpm gen:coverage


      - name: Release with semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
