name: Release

on:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write  # OIDC for npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@10.15.1 --activate
        
      - name: Setup Node
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install latest npm
        run: |
          echo "Current npm version: $(npm -v)"
          npm install -g npm@latest
          echo "Updated npm version: $(npm -v)"

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Verify signatures
        run: npm audit signatures

      - name: Generate features (web-features -> features.ts)
        run: pnpm gen:features

      - name: Build
        run: pnpm build

      - name: Run tests
        run: pnpm test

      - name: Generate coverage report (docs/coverage.md)
        run: pnpm gen:coverage

      - name: Release with semantic-release (Trusted Publishing)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
        run: |
          if [ -n "${NPM_CONFIG_USERCONFIG}" ] && [ -f "${NPM_CONFIG_USERCONFIG}" ]; then rm -f "${NPM_CONFIG_USERCONFIG}" || true; fi
          unset NODE_AUTH_TOKEN || true
          npx semantic-release@24.2.9
