name: Security Audit

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 9 * * 1" # Weekly, Mondays 09:00 UTC

permissions:
  contents: read

jobs:
  audit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@10.15.1 --activate

      - name: Setup Node LTS (22)
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: pnpm

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Audit production deps (high severity)
        run: pnpm audit --prod --audit-level high
